include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors: false
    avoid_print: false
    avoid_classes_with_only_static_members: false
