name: nane_client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  copy_with_extension: ^2.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  flutter_secure_storage: ^4.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  provider: ^5.0.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^1.12.2
  copy_with_extension_gen: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.0
  lint: ^1.5.3

flutter:
  uses-material-design: true
